# Generated by Django 5.0.4 on 2024-04-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=200)),
                ('jobtype', models.CharField(max_length=200)),
                ('role', models.TextField()),
                ('jobdescription', models.TextField()),
                ('qualifications', models.TextField()),
                ('gainsandbenefits', models.TextField()),
                ('additionalinformation', models.TextField()),
                ('banner', models.ImageField(upload_to='')),
            ],
        ),
    ]
