# Generated by Django 5.0.4 on 2024-04-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='banner',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
