# Generated by Django 5.0.4 on 2024-04-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_responsibilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=200)),
                ('jobtype', models.CharField(max_length=200)),
                ('role', models.TextField()),
                ('jobdescription', models.TextField()),
                ('responsibilities', models.TextField(blank=True)),
                ('qualifications', models.TextField()),
                ('gainsandbenefits', models.TextField()),
                ('additionalinformation', models.TextField()),
                ('banner', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
