# Generated by Django 5.0.4 on 2024-04-28 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_alter_jobapplication_resume_alter_joblisting_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='banner',
            field=models.ImageField(null=True, upload_to='static/images/'),
        ),
    ]
