# Generated by Django 5.0.4 on 2024-04-28 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alter_jobapplication_resume_alter_joblisting_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(upload_to='banner/images/'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='banner',
            field=models.ImageField(null=True, upload_to='banner/images/'),
        ),
    ]
