# Generated by Django 5.0.4 on 2024-05-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_alter_joblisting_banner_alter_listing_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='banner',
            field=models.ImageField(null=True, upload_to='listings/'),
        ),
    ]
